media:
  input: blog/assets
  output: ./assets
content:
  - name: posts
    type: collection
    path: blog
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: pubDate
        label: Published Date
        type: date
        options:
          format: MM dd yyyy
      - name: heroImage
        label: Hero Image
        type: image
    view:
      fields: [title, description, pubDate, heroImage]